# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_polyscape.ui'
#
# Created: Wed Feb 12 07:57:29 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(839, 562)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(470, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 821, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 781, 31))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 30, 571, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 571, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 110, 811, 31))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_5 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_2.addWidget(self.checkBox_5, 0, 3, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_2.addWidget(self.checkBox_8, 0, 4, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_2.addWidget(self.checkBox_7, 0, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_2.addWidget(self.checkBox_6, 0, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_2.addWidget(self.checkBox_9, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 131, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 170, 791, 31))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_15 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout_4.addWidget(self.checkBox_15, 0, 0, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout_4.addWidget(self.checkBox_16, 0, 1, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout_4.addWidget(self.checkBox_17, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 210, 171, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 300, 801, 211))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 791, 59))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_5.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.checkBox_18 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.horizontalLayout.addWidget(self.checkBox_18)
        self.checkBox_19 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.horizontalLayout.addWidget(self.checkBox_19)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 1, 1, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 80, 791, 59))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_6.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.checkBox_20 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.horizontalLayout_2.addWidget(self.checkBox_20)
        self.checkBox_21 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.horizontalLayout_2.addWidget(self.checkBox_21)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 140, 791, 59))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_7.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_7.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.checkBox_22 = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.horizontalLayout_3.addWidget(self.checkBox_22)
        self.checkBox_23 = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.horizontalLayout_3.addWidget(self.checkBox_23)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PolyScape (Prototype)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Ecosystem Services", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "Fuel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "Fibre", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Food", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Dialog", "Water", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("Dialog", "\"products obtained from ecosystems\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Provisioning services: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("Dialog", "\"benefits obtained from the regulation of ecosystem processes\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Regulating services:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Dialog", "Pollination", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("Dialog", "Pest and disease control", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Dialog", "Water regulation", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Dialog", "Carbon sequestration", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("Dialog", "Climate regulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("Dialog", "\"benefits obtained from the regulation of ecosystem processes\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Cultural services:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("Dialog", "Cultural, intellectual and spiritual inspiration", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("Dialog", "Recreational experiences", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("Dialog", "Scientific discovery", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Supporting services", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Data source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("Dialog", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("Dialog", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("Dialog", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setText(QtGui.QApplication.translate("Dialog", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Soil data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setText(QtGui.QApplication.translate("Dialog", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setText(QtGui.QApplication.translate("Dialog", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Land use", None, QtGui.QApplication.UnicodeUTF8))

